### ISSUE TITLE
tools package not found

### ISSUE THREAD

**Issue by Anastasu6ka** [fhamborg/Giveme5W#15]
Hi, 

I couldn't run the parse_documents.py because 
1) distance_of_candidate.py imported compibed_scoring.py from a subfolder even though it's in the same folder - easily solved 
2) environment_extractor.py required tools package, but firstly, it's kinda deprecated (https://pypi.python.org/pypi/tools) and secondly, if I found the correct library, it doesn't have any cache related modules. Which package it was supposed to be initially?

**Comment by bkrrrr** [comment]
Hi,

i guess you are using the fork, not this repo. 
Looks like both imports missing the  "extractor." in the import path.
```python
from **extractor**.tools.cache_manager import CacheManager

```

I can fix it, as soon the repo is transferred to the new owner. 

--
While developing with PyCharm these imports are fixed autom. by the IDE.

**Comment by Anastasu6ka** [comment]
Yeap, it helped. This missing of "extractor." part showed up in several more places for me.

I have a similar problem now with root in key_value_cache.py. Am I missing some path parts again or it's an external library?

**Comment by bkrrrr** [comment]
same,  "extractor." is missing.
Strange, i can run it even from a terminal without any problem.

**Comment by Anastasu6ka** [comment]
I assume it might happen because I add giveme5w as a second project root in pycharm, and the ide needs more details on what originates from where.
